application:
  name: posthog
  project: CHANGEME
  organization: CHANGEME
databases:
- name: my-psql
  type: postgresql
  version: 12
- name: my-redis
  type: redis
  version: 6
routers:
- name: posthog-router
  routes:
  - application_name: posthog
    paths:
    - "/"
